### PR TITLE
Viz engine

### PR DESCRIPTION
**Pull request by mbastian**

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks for adding tests Mathieu!

I think I noticed a typo where it says date instead of data, I checked this with the phone...

**Comment by eduramiba** [comment]
I just implemented some missing method to master that was used in viz-engine.

About edges quadtree removed, in most cases it's possible to not have it, but it was there because an edge can be on screen when none of its nodes are visible. In that case, the edge now disappears from screen. Maybe we can check a midpoint but it's not perfect and edges can still disappear.

**Comment by mbastian** [comment]
> I just implemented some missing method to master that was used in viz-engine.

Thanks, yeah I wasn't completely sure what you were using!

> 
> About edges quadtree removed, in most cases it's possible to not have it, but it was there because an edge can be on screen when none of its nodes are visible. In that case, the edge now disappears from screen. Maybe we can check a midpoint but it's not perfect and edges can still disappear.

This is also how it worked in the legacy engine and nobody ever complained so I think it's fine. In any event, it would be very complex to add the edge to all the quadtree nodes in between the source/target. Midpoint sounds like a hack to me.

**Comment by eduramiba** [comment]
Oh I see, yeah in most cases it's not noticed so we can leave it like that and avoid performance penalty.

**Pull request merged**
